#!/usr/bin/env python3
import os

v3_dir = "/Users/christopherhoar/Desktop/v3"
nav_js_file = os.path.join(v3_dir, "js", "nav.js")

print(f"Adding Communio link to navigation and footer in nav.js")

# Read the nav.js file
with open(nav_js_file, 'r', encoding='utf-8') as f:
    content = f.read()

# Update navigation menu items
old_nav = """const menuItems = [
  { text: 'About', href: '/v3/about.html', page: 'about' },
  { text: 'Initiatives', href: '/v3/initiatives.html', page: 'initiatives' },
  {
    text: 'Events',
    href: '/v3/events/index.html',
    page: 'events',
    dropdown: [
      { text: 'April 26 — Education, Youth & Technology', href: '/v3/events/april-26-education-youth-technology.html' },
      { text: 'May 24 — AI, Human Dignity & Communities', href: '/v3/events/may-24-ai-human-dignity-communities.html' }
    ]
  },
  { text: 'Insights', href: '/v3/insights.html', page: 'insights' },
  { text: 'Library', href: '/v3/library.html', page: 'library' },
  { text: 'Budapest Appeal', href: '/v3/budapest-appeal.html', page: 'budapest-appeal' },
  { text: 'Get Involved', href: '/v3/get-involved.html', page: 'get-involved' },
  { text: 'Contact', href: '/v3/contact.html', page: 'contact' }
];"""

new_nav = """const menuItems = [
  { text: 'About', href: '/v3/about.html', page: 'about' },
  { text: 'Initiatives', href: '/v3/initiatives.html', page: 'initiatives' },
  {
    text: 'Events',
    href: '/v3/events/index.html',
    page: 'events',
    dropdown: [
      { text: 'April 26 — Education, Youth & Technology', href: '/v3/events/april-26-education-youth-technology.html' },
      { text: 'May 24 — AI, Human Dignity & Communities', href: '/v3/events/may-24-ai-human-dignity-communities.html' }
    ]
  },
  { text: 'Insights', href: '/v3/insights.html', page: 'insights' },
  { text: 'Library', href: '/v3/library.html', page: 'library' },
  { text: 'Budapest Appeal', href: '/v3/budapest-appeal.html', page: 'budapest-appeal' },
  { text: 'Communio', href: '/v3/communio.html', page: 'communio' },
  { text: 'Get Involved', href: '/v3/get-involved.html', page: 'get-involved' },
  { text: 'Contact', href: '/v3/contact.html', page: 'contact' }
];"""

# Count occurrences before replacement
nav_count = content.count(old_nav)
print(f"Found {nav_count} occurrence(s) of navigation menu")

# Replace navigation
if nav_count > 0:
    content = content.replace(old_nav, new_nav)
    print("Updated navigation menu with Communio link")

# Update footer links
old_footer = """                <div class="footer-links">
                    <a href="/v3/insights.html">Insights</a>
                    <a href="/v3/library.html">Library</a>
                    <a href="/v3/index.html">Home</a>
                    <a href="/v3/about.html">About</a>
                    <a href="/v3/initiatives.html">Initiatives</a>
                    <a href="/v3/get-involved.html">Get Involved</a>
                    <a href="/v3/contact.html">Contact</a>
                    <a href="/v3/budapest-appeal.html">Budapest Appeal</a>
                    <a href="/v3/privacy.html">Privacy Policy</a>
                </div>"""

new_footer = """                <div class="footer-links">
                    <a href="/v3/insights.html">Insights</a>
                    <a href="/v3/library.html">Library</a>
                    <a href="/v3/index.html">Home</a>
                    <a href="/v3/about.html">About</a>
                    <a href="/v3/initiatives.html">Initiatives</a>
                    <a href="/v3/communio.html">Communio</a>
                    <a href="/v3/get-involved.html">Get Involved</a>
                    <a href="/v3/contact.html">Contact</a>
                    <a href="/v3/budapest-appeal.html">Budapest Appeal</a>
                    <a href="/v3/privacy.html">Privacy Policy</a>
                </div>"""

# Count occurrences before replacement
footer_count = content.count(old_footer)
print(f"Found {footer_count} occurrence(s) of footer links")

# Replace footer
if footer_count > 0:
    content = content.replace(old_footer, new_footer)
    print("Updated footer links with Communio link")

# Write the updated content back
with open(nav_js_file, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\nTotal updates: {nav_count + footer_count}")
print("nav.js has been updated successfully!")
print("\nNote: Since nav and footer are generated by JavaScript, all HTML pages will automatically get the Communio link.")