from pathlib import Path

test_file = Path('lvii-world-day-of-peace-2024-artificial-intelligence-and-peace.html')
content = test_file.read_text()

old_header = '    <!-- Header dynamically populated by dcf-ui.js -->\n    <div id="dcf-header"></div>'
new_header = '''    <header class="header">
        <nav class="nav-container">
            <a href="../index.html" class="logo"><!-- Logo dynamically generated by dcf-ui.js --></a>
            <ul class="nav-menu" id="navMenu">
                <!-- Populated by dcf-ui.js -->
            </ul>
            <div class="user-menu">
                <div class="language-buttons">
                    <button onclick="changeLanguage('en')" class="lang-btn">EN</button>
                    <button onclick="changeLanguage('it')" class="lang-btn">IT</button>
                    <button onclick="changeLanguage('es')" class="lang-btn">ES</button>
                    <button onclick="changeLanguage('hu')" class="lang-btn">HU</button>
                </div>
            </div>
        </nav>
    </header>'''

content = content.replace(old_header, new_header)

old_footer = '    <!-- Footer dynamically populated by dcf-ui.js -->\n    <div id="dcf-footer"></div>'
new_footer = '    <footer class="dcf-footer"></footer>'

content = content.replace(old_footer, new_footer)

Path('test-fixed.html').write_text(content)
print("Done - check test-fixed.html")
